
import argparse
from pathlib import Path

Parser = argparse.ArgumentParser(description="Generates a sublime project file")
Parser.add_argument("manifest",
                    type=Path,
                    help="The repo manifest as generated by the init script.")

Args = Parser.parse_args()

FileTemplate = """{{
  "build_systems":
  [
    {{
      "cmd":
      [
        "${{folder}}/Utilities/FASTBuild/FBuild.exe",
        "-ide",
        "VulkanExperiments"
      ],
      "file_regex": "([A-z]:.*?)\\\\(([0-9]+)(?:,\\\\s*[0-9]+)?\\\\)",
      "name": "VulkanExperiments",
      "variants":
      [
        {{
          "cmd":
          [
            "${{folder}}/Utilities/FASTBuild/FBuild.exe",
            "-ide",
            "Tests"
          ],
          "name": "Tests: Build Only"
        }},
        {{
          "cmd":
          [
            "${{folder}}/Utilities/FASTBuild/FBuild.exe",
            "-ide",
            "Tests-Run"
          ],
          "name": "Tests: Build and Run"
        }},
        {{
          "cmd":
          [
            "${{folder}}/Utilities/FASTBuild/FBuild.exe",
            "-ide",
            "-clean"
          ],
          "name": "Rebuild"
        }}
      ],
      "working_dir": "${{folder}}"
    }}
  ],
  "folders":
  [
    {{
      "path": "."
    }},
    {{
      "path": "{Windows10SDKPath}/Include/{Windows10SDKVersion}",
      "name": "Windows Kit {Windows10SDKVersion}",
      "file_include_patterns": [ "*.h" ]
    }},
    {{
      "path": "{VS2015Path}/VC",
      "name": "Visual Studio 2015 / VC",
      "file_include_patterns": [ "*.h" ]
    }},
    {{
      "path": "{VulkanSDK}",
      "name": "Vulkan SDK",
      "file_include_patterns": [ "*.h", "*.hpp" ]
    }}
  ]
}}"""

FileArgs = {}

with Args.manifest.open("r") as InFile:
  # TODO These are hardcoded for now. Read them from Args.manifest (JSON?) once we have that.
  FileArgs["VS2015Path"]          = "C:/Program Files (x86)/Microsoft Visual Studio 14.0"
  FileArgs["Windows10SDKPath"]    = "C:/Program Files (x86)/Windows Kits/10"
  FileArgs["Windows10SDKVersion"] = "10.0.10586.0"
  FileArgs["VulkanSDK"]           = "C:/VulkanSDK/1.0.13.0"

#
# Print The Result
#
Formatted = FileTemplate.format(**FileArgs)
print(Formatted, end='\n')
